# -*- coding: utf-8 -*-
"""NRF05_LR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kJJgb6zsbg6fjKU-FAKda9QAy6UHfOu_
"""

from sklearn.datasets import load_digits # digit dataset

# load dataset
digits = load_digits()

# features and target
X = digits.data / digits.data.max()
y = digits.target

from sklearn.linear_model import LogisticRegression # LR for classification
from sklearn.model_selection import train_test_split # split訓練及測試資料

# split dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=0) # 依2:1隨機切割出training set and test set

# fit data
clf = LogisticRegression(solver='lbfgs', max_iter=1000, multi_class='multinomial', random_state=0) # max_iter: 迭代次數
clf.fit(X_train, y_train)

# outside prediction
y_pred_test = clf.predict(X_test)

# inside prediction
y_pred_train = clf.predict(X_train)

# calculate performance
acc_outside = sum((y_test - y_pred_test)==0) / len(y_test) * 100
acc_inside = sum((y_train - y_pred_train)==0) / len(y_train) * 100

print('LR')
print("inside accuracy: {:.2f}%".format(acc_inside))
print("outside accuracy: {:.2f}%".format(acc_outside))